name = "d1-collect-ips"
compatibility_date = "2023-10-01"

[env]
  
[[d1_databases]]
binding = "github_actions_ips"
database_name = "github_actions_ips"
database_id = "471ffebe-9e6c-478a-8437-d4dd7477b674"
