name: Ping Cloudflare Worker

on:
    schedule:
      - cron: "*/5 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Worker
        run: |
          curl -s "https://<your-worker>.workers.dev?secret=${{ secrets.SECRET }}"
      
